<form
    action="<?=APP::config('url') ?>rijeka/novo"
    method="POST">

    <fieldset class = "fieldset">
    <legend>Osnovni podaci o rijeci</legend>
  
    <label>Naziv rijeke
        <input type="text" name="naziv" value="<?=$rijeka->naziv?>"/>
    </label>

    <label>Dužina rijeke
        <input type="text" name="duzina" value="<?=$rijeka->duzina?>" />
    </label>

    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <input type="submit" class="button expanded" 
                value="Unesite novu rijeku!"></input>
        </div>
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" href="<?=APP::config('url') ?>rijeka/index">
        Odustani!
        </a>
        </div>
    </div>

    </fieldset>
</form>
