<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="example-menu"></button>
  <div class="title-bar-title"><?=APP::config('nazivAPP') ?></div>
</div>

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>
      <a href="<?=APP::config('url') ?>">
        <i class="fas fa-home"></i>
</a>
    </li> 

      <li><a href="<?=APP::config('url') ?>index/oribolovu">
      <i class="fas fa-fish"></i> O ribolovu
      </a>
      </li>
      
      <?php if(isset($_SESSION['autoriziran'])): ?>
        <li>
        <a href="#">Podaci</a>
        <ul class="menu vertical">
          <li><a href="<?=APP::config('url') ?>nadzornaploca/index">Nadzorna ploča</a></li>
          <li><a href="<?=APP::config('url') ?>clanudruge/index">Članovi</a></li>
          <li><a href="<?=APP::config('url') ?>riba/index">Ribe</a></li>
          <li><a href="<?=APP::config('url') ?>rijeka/index">Rijeke</a></li>
          <li><a href="<?=APP::config('url') ?>pecanje/index">Pecanje</a></li>
          <?php if($_SESSION['autoriziran']->uloga==='admin'): ?>
            <li><a href="<?=APP::config('url') ?>operater/index">Operateri</a></li>
          <?php endif;  ?>
        </ul>
      </li>
       
      <?php endif;  ?>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
    <li>
      <?php if(!isset($_SESSION['autoriziran'])): ?>
      <a href="<?=APP::config('url') ?>index/login">
      <i class="fas fa-sign-in-alt"></i>
      </a>
      <?php else:  ?>
      <a href="<?=APP::config('url') ?>index/logout">
      <i class="fas fa-sign-out-alt"></i>
      </a>
      <?php endif;  ?>
    </li>
    </ul>
  </div>
</div>