<a class="button expanded success" href="<?=APP::config('url') ?>clanudruge/novo">
<i class="fas fa-user-plus"></i> Dodaj novog člana
</a>

<form action="<?=APP::config('url') ?>clanudruge/index" method="get">
<input type="text" name="uvjet" value="<?=$uvjet?>" 
placeholder="Unesite dio imena,prezimena ili OIB-a">
</form>

<nav aria-label="Pagination">
  <ul class="pagination text-center">
    <li class="pagination-previous"><a href="<?=APP::config('url') ?>clanudruge/index?stranica=<?=$prethodna?>&uvjet=<?=$uvjet?>" aria-label="Previous page">Prethodna stanica</a></li>
    <li class="current"><span class="show-for-sr">Vi ste na</span><?=$trenutna?>/<?=$ukupnoStranica?></li>
    <li class="pagination-next"><a href="<?=APP::config('url') ?>clanudruge/index?stranica=<?=$slijedeca?>&uvjet=<?=$uvjet?>" aria-label="Next page">Slijedeća stranica</a></li>
  </ul>
</nav>
<div style='overflow-x:auto'>
<table cellpadding=5 border=1 cellspacing=0>
    <thead>
        <tr>
            <th>Ime</th>
            <th>Prezime</th>
            <th>OIB</th>
            <th>Broj dozvole</th>
            <th>Radnja</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($clanovi as $clan): ?>
            <tr>
                <td><?=$clan->ime?></td>
                <td><?=$clan->prezime?></td>
                <td><?=$clan->oib?></td>
                <td><?=$clan->brojdozvole?></td>
                <td>
                
                <a href="<?=APP::config('url') ?>clanudruge/promjena?sifra=<?=$clan->sifra?>&stranica=<?=$trenutna?>">
                <?php include BP . 'view/predlozak/izgledPromijeni.phtml' ?>
                </a>
                
                <?php if($clan->pecanje==0): ?>
                <a  onclick="return confirm('Jeste li sigurni da želite obrisati?');"
                href="<?=APP::config('url') ?>clanudruge/brisanje?sifra=<?=$clan->sifra?>">
                <?php include BP . 'view/predlozak/izgledObrisi.phtml' ?>
                </a>
                <?php endif; ?>
                </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</div>

<nav aria-label="Pagination">
  <ul class="pagination text-center">
    <li class="pagination-previous"><a href="<?=APP::config('url') ?>clanudruge/index?stranica=<?=$prethodna?>&uvjet=<?=$uvjet?>" aria-label="Previous page">Prethodna </a></li>
    <li class="current"><span class="show-for-sr">Vi ste na</span><?=$trenutna?>/<?=$ukupnoStranica?></li>
    <li class="pagination-next"><a href="<?=APP::config('url') ?>clanudruge/index?stranica=<?=$slijedeca?>&uvjet=<?=$uvjet?>" aria-label="Next page">Slijedeća </a></li>
  </ul>
</nav>
