<?php

?>

<a class="button expanded success" href="#">
    <?php include BP . 'view/predlozak/izgledDodajnovi.phtml' ?>
</a>

<table class="table"> 
    <thead>
        <tr>
            <th>Ime</th>
            <th>Prezime</th>
            <th>Oib</th>
            <th>Broj dozvole</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($clanovi as $clan): ?>
            <tr>
                <td><?=$clan->ime?></td>
                <td><?=$clan->prezime?></td>
                <td><?=$clan->oib?></td>
                <td><?=$clan->brojdozvole?></td>
                <td>
                <a href="#">
                <?php include BP . 'view/predlozak/izgledPromijeni.phtml' ?>
                </a>
                <a href="#">
                <?php include BP . 'view/predlozak/izgledObrisi.phtml' ?>
                </a>
                </td>
        </tr>

        <?php endforeach; ?>
    </tbody>
</table>