<form
    action="<?=APP::config('url') ?>clanudruge/promjena"
    method="POST">
  
    <label>Ime
        <input type="text" name="ime" value="<?=$clanudruge->ime?>"/>
    </label>

    <label>Prezime
        <input type="text" name="prezime" value="<?=$clanudruge->prezime?>" />
    </label>

    <label>Oib
        <input type="number" name="oib" value="<?=$clanudruge->oib?>" />
    </label>

    <label>Broj dozvole
        <input type="number" name="brojdozvole" value="<?=$clanudruge->brojdozvole?>" />
    </label>

    <input type="hidden" name="sifra" value="<?=$clanudruge->sifra?>">

    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <input type="submit" class="button expanded" 
                value="Promijeni!"></input>
        </div>
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" href="<?=APP::config('url') ?>clanudruge/index?stranica=<?=$trenutna?>">
        Odustani!
        </a>
        </div>
    </div>
        
</form>
