<a class="button expanded success" 
href="<?=APP::config('url') ?>riba/novo">
<i class="fas fa-user-plus"></i> Dodaj novu ribu
</a>

<div class="grid-x grid-margin-x">
    <?php foreach($ribe as $riba): ?>
    <div class="large-3 medium-6 cell" style="text-align: center">
        <div class="callout" style="min-height: 520px">
             <h1 style="font-size: 1.5em"><?=$riba->naziv?></h1>
             <hr />
             <?php if(file_exists(BP. 'public' . DIRECTORY_SEPARATOR 
            . 'img' . DIRECTORY_SEPARATOR . 'riba'
            . DIRECTORY_SEPARATOR . $riba->sifra . '.png')):?>
            
            <img class="slika" id="r_<?=$riba->sifra?>" src="<?=APP::config('url') ?>public/img/riba/<?=$riba->sifra?>.jpg" alt="<?=$riba->naziv?> ">  
             <?php else: ?>
             <img class="slika" id="r_<?=$riba->sifra?>" src="<?=APP::config('url') ?>public/img/nepoznatariba.png" alt="<?=$riba->naziv?> ">
             <?php endif; ?>
             <hr />

Početak lovostaja: <?=$riba->pocetaklovostaja?><br />
Kraj lovostaja: <?=$riba->krajlovostaja?><br />
Opis: <?=$riba->opis?><br />
        <hr />
        
<a href="<?=APP::config('url') ?>riba/promjena?sifra=<?=$riba->sifra?>">
    <?php include BP . 'view/predlozak/izgledPromijeni.phtml' ?>
</a>

<?php if($riba->pecanje==0): ?>
<a  onclick="return confirm('Jeste li sigurni da želite obrisati?');"
    href="<?=APP::config('url') ?>riba/brisanje?sifra=<?=$riba->sifra?>">
    <?php include BP . 'view/predlozak/izgledObrisi.phtml' ?>
</a>
<?php endif; ?>

        </div>
    </div>

    <?php endforeach; ?>
</div>

<div class="reveal" id="slikaModal" data-reveal>
  <img id="image" src="" alt="" />
  <input type="file" id="inputImage" name="file" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff">
  <a href="#" id="spremi">Spremi</a>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>