<form
    action="<?=APP::config('url') ?>riba/promjena"
    method="POST">
  
    
    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
            <label>Naziv
            <input type="text" name="naziv" value="<?=$ribe->naziv?>"/>
        </label>
    </div>
        <div class="large-6 small-12 cell">
        <label>Početak lovostaja
        <input type="date" name="pocetaklovostaja" value="<?=$ribe->pocetaklovostaja?>" />
        </label>
    </div>       
        <div class="large-6 small-12 cell">
        <label>Kraj lovostaja
        <input type="date" name="krajlovostaja" value="<?=$ribe->krajlovostaja?>" />
        </label>
    </div>  
        <div class="large-6 small-12 cell">
        <label>Opis
        <textarea name="opis" cols="30"
        rows="5"><?=$ribe->opis?></textarea>
        </label>
    </div>    
</div>   

    <input type="hidden" name="sifra" value="<?=$ribe->sifra?>">

    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <input type="submit" class="button expanded" 
                value="Promijeni ribu"></input>
        </div>
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" href="<?=APP::config('url') ?>riba/index">
        Odustani!
        </a>
        </div>
    </div>
        
</form>
