<form
    action="<?=APP::config('url') ?>pecanje/novo"
    method="POST">
  
    <label>Datum
        <input type="date" name="datum" value="<?=$pecanje->datum?>"/>
    </label>

    <label>Član udruge
       <select name="clanovi" id="clanovi">
       <option <?php if($pecanje->clan==0){
    echo '  selected="selected"  ';
}?> value="0">Odaberite člana</option>
       <?php foreach($clanovi as $clan) : ?>
        <option <?php if($pecanje->clan==$clan->sifra){
            echo '  selected="selected"  ';
        }?> value="<?=$clan->sifra?>"><?=$clan->ime?> <?=$clan->prezime?></option>
         <?php endforeach; ?>
       </select>
    </label>

    <label>Riba
       <select name="riba" id="riba">
       <option <?php if($pecanje->riba==0){
    echo '  selected="selected"  ';
}?> value="0">Odaberite ribu</option>
       <?php foreach($ribe as $riba) : ?>
        <option <?php if($pecanje->riba==$riba->sifra){
            echo '  selected="selected"  ';
        }?> value="<?=$riba->sifra?>"><?=$riba->naziv?></option>

     <?php endforeach; ?>
       </select>
    </label>

    <label>Količina
        <input type="text" name="kolicina" value="<?=$pecanje->kolicina?>"/>
    </label>

    <label>Težina
        <input type="text" name="tezina" value="<?=$pecanje->tezina?>"/>
    </label>

    <label>Rijeka
       <select name="rijeka" id="rijeka">
       <option <?php if($pecanje->rijeka==0){
    echo '  selected="selected"  ';
}?> value="0">Odaberite rijeku</option>
       <?php foreach($rijeke as $rijeka) : ?>
        <option <?php if($pecanje->rijeka==$rijeka->sifra){
            echo '  selected="selected"  ';
        }?> value="<?=$rijeka->sifra?>"><?=$rijeka->naziv?></option>

     <?php endforeach; ?>
       </select>
    </label>

    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <input type="submit" class="button expanded" 
                value="Unesite novi ulov!"></input>
        </div>
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" href="<?=APP::config('url') ?>pecanje/index">
        Odustani!
        </a>
        </div>
    </div>
        
</form>
