<form
    action="<?=APP::config('url') ?>pecanje/promjena"
    method="POST">
  
    <label>Datum
        <input type="date" name="datum" id="datum" value="<?=$entitet->datum?>"/>
    </label>

    <label>Član udruge
       <select name="clanudruge" id="clanudruge">
       <option <?php if($entitet->clanudruge==0){
    echo '  selected="selected"  ';
}?> value="0">Odaberite člana</option>
       <?php foreach($clanudruge as $clan) : ?>
        <option <?php if($entitet->clanudruge==$clan->sifra){
            echo '  selected="selected"  ';
        }?> value="<?=$clan->sifra?>"><?=$clan->ime?> <?=$clan->prezime?></option>
         <?php endforeach; ?>
       </select>
    </label>

    <label>Riba
       <select name="riba" id="riba">
       <option <?php if($entitet->riba==0){
    echo '  selected="selected"  ';
}?> value="0">Odaberite ribu</option>
       <?php foreach($ribe as $riba) : ?>
        <option <?php if($entitet->riba==$riba->sifra){
            echo '  selected="selected"  ';
        }?> value="<?=$riba->sifra?>"><?=$riba->naziv?></option>

     <?php endforeach; ?>
       </select>
    </label>

    <label>Količina
        <input type="text" name="kolicina" id="kolicina" value="<?=$entitet->kolicina?>"/>
    </label>

    <label>Težina
        <input type="text" name="tezina" id="tezina" value="<?=$entitet->tezina?>"/>
    </label>

    <label>Rijeka
       <select name="rijeka" id="rijeka">
       <option <?php if($entitet->rijeka==0){
    echo '  selected="selected"  ';
}?> value="0">Odaberite rijeku</option>
       <?php foreach($rijeke as $rijeka) : ?>
        <option <?php if($entitet->rijeka==$rijeka->sifra){
            echo '  selected="selected"  ';
        }?> value="<?=$rijeka->sifra?>"><?=$rijeka->naziv?></option>

     <?php endforeach; ?>
       </select>
    </label>


    
    <input type="hidden" name="sifra" value="<?=$entitet->sifra?>">
    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <input type="submit" class="button expanded" 
                value="Promijenite ulov!"></input>
        </div>
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" href="<?=APP::config('url') ?>pecanje/index">
        Odustani!
        </a>
        </div>
    </div>
        
</form>
