<h3>Ribolov</h3>
<h6>Ribolov je aktivnost lova riba. Riječ ribolov se također koristi i za lov na druge životinje koje žive u vodi kao što su razne školjke, rakovi, lignje, sipe, hobotnice, kornjače i druge kralježnjake, jedino se za kitove koristi pojam kitolov. Ribolov je stara i široko rasprostranjena aktivnost sa raznim tehnikama i tradicijama, ali i primjenom modernih tehnoloških pomagala.
Razlikujemo sportski i komercijalni ribolov te slatkovodni i morski.</h6>

<h3>Športski ribolov na slatkim vodama</h3>
<div><h6>Športski ribolov na slatkim vodama regulirano je "Zakonom o slatkovodnom ribarstvu" te "Pravilnikom o športskom ribolovu u slatkovodnom ribarstvu". Navedeni tekstovi Zakona dostupni su na web stranicama "Narodnih novina".
Za obavljanje športskog ili rekreacijskog ribolova na određenom ribolovnom području ribiči kupuju dozvole od ovlaštenika ribolovnog prava koje vrijede samo na ribolovnoj zoni za koju ovlaštenik posjeduje ribolovno pravo. 
Ako su ovlaštenici zaključili ugovor o recipročnom pravu ribolova na terenima drugog ribolovnog društva, kupnjom dodatne, često jeftinije dozvole moguće je bavljenje športsko-rekreacijskim ribolovom i na ribolovnom području tog društva.
Na području Republike Hrvatske postoji cca 120 ovlaštenika ribolovnog prava, iako je aktivnih športsko-ribolovnih udruga oko 450. Dozvole za ribolov izdaje "Ministarstvo poljoprivrede, ribarstva i ruralnog razvoja" putem ovlaštenika ribolovnog prava.
Dozvole na obavljanje ribolova moguče je kupiti za sljedeća razdoblja:
-- jedan dan (dnevna dozvola)
-- tekuću kalendarsku godinu (godišnja dozvola)

Popis ovlaštenika ribolovnog prava ribiči mogu lako naći na web stranicama "Hrvatskog športskog ribolovnog saveza".
Najčešće korištena oprema slatkovodnog ribolova uključuje štap sa rolom ili koturom te se izvodi sa nekoliko standardnih tehnika ribolova: Ribolov na dnu (grunt), ribolov plovkom, spinning (špinanje, varaličarenje) te mušičarenje. 
Najčešća lovina uključuje sljedeće riblje vrste: šaran, štuka, linjak, pastrva, deverika, som, babuška. Šaran je najpoznatija vrsta koja se lovi na vodama, a i kao pojedinačni sport na natjecanjima.</h6></div>

<h3>Tehnike ribolova</h3>
<div><h6>Od tehnika ribolova na moru najčešće se koriste sljedeće: panula, povraz (kod ribolova sa obale), kanjčenica (kod ribolova sa brodice), parangal, spinning, trolling te posebne kategorije podvodni ribolov i Big game fishing. Navedenim tehnikama najčešće se love, od riba: luben, komarča, šarag, ovčica, špar, pic, ušata, zubatac, tuna, te od glavonožaca: lignja, sipa, hobotnica.</h6></div>